[build]
  publish = "."

[[redirects]]
  from = "/api/consent"
  to = "/.netlify/functions/consent"
  status = 200

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200
